"$schema" = 'https://starship.rs/config-schema.json'

format = """$os\
$username\
$directory\
$git_branch\
$git_status\
$cmd_duration\
$character"""

palette = 'tokyo_night'
command_timeout = 200

[os]
disabled = false
format = '[$symbol](fg:foreground) '

[os.symbols]
Macos = ""

[username]
show_always = true
format = "[$user]($style) "
style_root = "fg:red bold"
style_user = "fg:foreground"

[directory]
style = "fg:foreground"
format = '[$path]($style) '
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "fg:comment"
format = '[$symbol $branch]($style) '

[git_status]
style = "fg:orange"
format = '[$all_status$ahead_behind]($style)'

[cmd_duration]
show_milliseconds = false
format = '[took $duration](fg:comment) '
min_time = 2000

[character]
success_symbol = '[❯](fg:green)'
error_symbol = '[❯](fg:red)'
vimcmd_symbol = '[❮](bold fg:green)'
vimcmd_replace_one_symbol = '[❮](bold fg:purple)'
vimcmd_replace_symbol = '[❮](bold fg:purple)'
vimcmd_visual_symbol = '[❮](bold fg:yellow)'

[palettes.tokyo_night]
foreground = "#c0caf5"
comment = "#565f89"
red = "#f7768e"
orange = "#ff9e64"
yellow = "#e0af68"
green = "#9ece6a"
cyan = "#2ac3de"
blue = "#7aa2f7"
purple = "#bb9af7"
magenta = "#ff007c"
